[package]
name = "raytracer"
version = "0.1.0"
authors = ["jeffb"]
edition = "2018"

[dependencies]
nalgebra-glm = "0.1"
png = "0.14.0"
rand = "0.6.5"
piston = "0.42.0"
piston_window = "0.89.0"
image = "0.21.0"
vecmath = "0.3.1"
gfx = "0.18.0"
gfx_device_gl = "0.16.0"
gfx_core = "0.9.0"
